services:
  pharmacies:
    container_name: pharmacies
    build: ./compose
    restart: always
    env_file:
      - .env
    volumes:
      - "./src:/var/www/html"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.pharmacies.rule=Host(\"${DOMAIN}\")"
      - "traefik.http.routers.pharmacies.entrypoints=websecure"
      - "traefik.http.routers.pharmacies.tls.certresolver=myresolver"
    networks:
      web:
      mariadb:
networks:
  web:
    name: web
    external: true
